---
version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - clickhouse-network

  clickhouse-1: &clickhouse-1
    image: clickhouse/clickhouse-server:23.3.1.2823
    ports:
      - "8123:8123"
    networks:
      - clickhouse-network
    depends_on:
      - zookeeper
    restart: always
    environment:
      CH_SHARD: 1
    volumes:
      - type: bind
        source: ./configs/clickhouse/users.d/
        target: /etc/clickhouse-server/users.d/
      - type: bind
        source: ./configs/clickhouse/config.d/
        target: /etc/clickhouse-server/config.d/
      - type: bind
        source: ./queries/
        target: /tmp/queries/

  clickhouse-2:
    <<: *clickhouse-1
    environment:
      CH_SHARD: 2
    ports:
      - "8124:8123"

  clickhouse-3:
    <<: *clickhouse-1
    environment:
      CH_SHARD: 3
    ports:
      - "8125:8123"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - clickhouse-network
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - type: bind
        source: ./scripts/
        target: /scripts/

networks:
  clickhouse-network:
