---
name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Create the lab
        run: |
          make create
      - name: Produce messages
        run: |
          make topic-produce-messages
      - name: Check lag
        run: |
          make topic-lag
      - name: Check the number of messgaes in ClickHouse
        run: |
          make clickhouse-messages-count
