---
name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create the lab
        run: |
          make create

      - name: Produce messages
        run: |
          make topic-produce-messages

      - name: Check messages in the topic
        run: |
          make topic-consumer

      - name: Check lag
        run: |
          make topic-lag

      - name: Check the number of messgaes in ClickHouse
        run: |
          make clickhouse-messages-count
